### ISSUE TITLE
Analyze sheet usage, similar to what was available in on-prem Qlik

### ISSUE THREAD

**Issue by jurajmisina** [qlik-oss/qlik-cloud-entitlement-analyzer#16]
## Add data about sheet usage

In on-prem Operations monitor app, there was an sheet tracking usage of app sheets, which enabled us to implement life-cycle management app or Qlik environments and make regular cleanups of unused sheets.

### Motivation

Currently we are not able to identify which sheets are used and which are not. This means we cannot clean unused sheets and we must rely on users to clean their own sheets regularly. But this also applies to public sheets. There's no point of maintaining sheets which are not used. Or perhaps we need to work on user enablement.

Looking at the API documentation it seems this is not possible with data the API provides right now. Is somethings like this on the roadmap?

**Comment by withdave** [comment]
Thanks @jurajmisina for the issue. There is nothing today, but it is an item that's on the roadmap.

I'll close this ticket for now since this repo is for the entitlement analyzer app, but I encourage you to head over to [Ideation](https://community.qlik.com/t5/Ideation/ct-p/qlik-product-insight) on the Qlik Community, look for an idea called `Qlik SaaS Sheet usage tracking` and add your vote and any comments!

Thanks!
