### ISSUE TITLE
Entitlement analyzer error

### ISSUE THREAD

**Issue by RamiSmt** [qlik-oss/qlik-cloud-entitlement-analyzer#29]
Hello ,
I have a  problem with The Entitlement analyzer app , it has not load historical data , i have only data for current month , also the calendar has only data for this month !
All other months data is null
<img width="956" alt="Capture d'écran 2024-04-17" src="https://github.com/qlik-oss/qlik-cloud-entitlement-analyzer/assets/167300324/7e40e3dd-182b-4bcd-8d9e-bf51105db503">

**Comment by withdave** [comment]
Hi @RamiSmt 

This is by design. Some of the endpoints used in this application only provide data for the month, so when doing a full load it aligns this across all data in the app to ensure you don't have some sections with more data than others. After this first load, it will store and maintain a history of data each time it reloads.

A little more detail on the community: https://community.qlik.com/t5/Support-Updates/Entitlement-Analyzer-for-Qlik-Sense-Enterprise-SaaS-Cloud-only/bc-p/1817836/highlight/true#M1694
